name: CI

on:
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run deploy

name: Set Git user identity
  run: |
    git config --local user.name iluhaar	
    git config --local user.email iluhaar@gmail.com